export const ADD_COMMENT= 'ADD_COMMENT'

export const LOAD_COMMENTS='LOAD_COMMENTS'
export const COMMENT_LOADING='COMMENT_LOADING'


export const LOAD_DISHES= 'LOAD_DISHES'
export const DISH_LOADING='DISH_LOADING'